@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites

!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/mongodb.puml
!includeurl ICONURL/devicons/mysql.puml
!includeurl SPRITESURL/kafka.puml
!includeurl SPRITESURL/server.puml

!includeurl ICONURL/font-awesome/mobile_phone.puml

!includeurl ICONURL/font-awesome-5/laptop.puml
!includeurl ICONURL/font-awesome-5/tablet_alt.puml
!includeurl ICONURL/font-awesome-5/calculator.puml
!includeurl ICONURL/font-awesome-5/chart_line.puml

left to right direction

package "Producers" {
    FA_MOBILE_PHONE(producer1, Phones) #LightBlue
    FA5_LAPTOP(producer2, Laptops) #LightBlue
    FA5_TABLET_ALT(producer3, Tablets) #LightBlue   
}

package "Data Aquisition" {
    queue "<$kafka>" as kafka #LightBlue
    rectangle "Spark Streaming" as spark #LightBlue
}

rectangle "Airflow" as airflow #LightBlue
'airflow : <img:https://upload.wikimedia.org/wikipedia/commons/d/de/AirflowLogo.png>


DEV_MYSQL(mysql, MySQL) #LightBlue

package "BI Analytics" {
    FA5_CALCULATOR(bi, KPI Calc) #LightPink
    FA5_CHART_LINE(dashboard, Dashboard) #LightPink
}


producer1 --> kafka
producer2 --> kafka
producer3 --> kafka

kafka <--> spark

spark --> mysql
bi <--> mysql
dashboard <--> mysql
airflow --> bi

legend right
    |Color | Type |
    |<#LightBlue>| Data Engineering|
    |<#LightPink>| BI Analytics|
endlegend

@enduml