@startuml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites

!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons/mongodb.puml
!includeurl ICONURL/font-awesome-5/store.puml
!includeurl SPRITESURL/kafka.puml
!includeurl SPRITESURL/server.puml

left to right direction

package "Producers" {
    FA5_STORE(store1, Store)
    FA5_STORE(store2, Store)
    FA5_STORE(store3, Store)
}

queue "<$kafka>" as kafka
rectangle "Spark Streaming" as spark

DEV_MONGODB(mongo, MongoDB)

store1 --> kafka
store2 --> kafka
store3 --> kafka

kafka <--> spark

spark --> mongo


@enduml