@startuml

left to right direction


class Producer {
    +userActorsInfo
    +userStoreRef
    +contentStoreRef
}

class ContentStore {
    +latestPictureIndex
    +latestVideoIndex
    +receive()
    __ supported msg __
    +AddPicture
    +AddVideo
} 

class UserStore {
    +latestUserIndex
    +receive()
    __ supported msg __
    +addUser
}

class User {
    +requests
    __ supported msg __
    +CreateUser
    +ShareContent
} 

Producer --> User : msg: Create a User
User --> User : msg: ShareContent (with time interval)
User <--> UserStore : msg: Add a new user
User --> ContentStore : msg: Add a new content
@enduml